### ISSUE TITLE
Why is write access to the target repository necessary?

### ISSUE THREAD

**Issue by krlmlr** [dessant/move-issues#3]
Thanks for the probot, it saves a lot of hassle.

Is it technically possible for the API to create issues in repos where the user doesn't have write access to? It seems possible via the API, but maybe the probot runs with a different scope?

I imagine a following mode of operation:

Me:

> /move to foo/bar

Probot:

> You don't have write access to foo/bar, and you haven't filed an issue there yet. (or: ..., you have already filed 34 issues there.) If you're sure, please issue the command "/move to foo/bar please"

Me:

> /move to foo/bar please

Probot:

> *sigh* Okay.

I see that this makes it easy to abuse the service, but the necessary confirmation should remove the possibility of accidental misspellings.

Reference: https://github.com/tidyverse/dplyr/issues/3633#issuecomment-394970682, CC @romainfrancois.

**Comment by dessant** [comment]
The API allows opening the issue, though write access is required to prevent people from deliberately spamming other repositories through the app. I understand that this may be an inconvenience, but I don't currently see a better option for preventing spam.

**Comment by romainfrancois** [comment]
Is it that much of a problem between two repos of the same organisation ?

**Comment by dessant** [comment]
That's a great point, target access could be required only when the owners of the source and target repository are different.

**Comment by krlmlr** [comment]
Thanks. Same org is useful, perhaps it's even enough to check if the user is member of the target org.

The "sudo mode" I'm suggesting takes care of accidental spamming. I think GitHub has its own policies in place against malicious spamming, but you might want to check with them -- it would be too bad if the "move bot" was banned when it's in fact the user who's responsible.

**Comment by dessant** [comment]
Team membership is also a possibility, but it's a bit tricky, because having access to that part of the API would require a new app permission that has to be accepted by current installations, and the membership could still be set as private. Though you're right that it could be checked for before falling back to requiring write access.

Thanks for your input guys, the linked commit was deployed. I'll look into these things and see where could the friction be further reduced.

**Comment by dessant** [comment]
Regarding the sudo mode, I'm not sure it would be that useful. The likelihood of misspelling the owner in `foo/bar` and still getting a repository that exists should be rather small and probably not worth the dev time. Its unlikely that GitHub would ban the app because of a malicious user, but they'd probably ask to ensure that it is not used as an open relay for opening issues and making comments.
