### ISSUE TITLE
zeroconfig option?

### ISSUE THREAD

**Issue by PatrickHeneise** [dessant/move-issues#8]
A friend just sent me the link and I think this is awesome! I wonder if it works without creating the `github/move.yml` file, if I'm OK with the default settings? It says "The file can be empty", that implies the file needs to be there? Our projects have >10 repos each, so I'd like to avoid adding the empty file to all repos.

**Comment by PatrickHeneise** [comment]
How can I test this? I'm wondering if I can replace this:

```
if (!repoConfig) {
  repoConfig = context;
}
```

**Comment by dessant** [comment]
This should work:
```js
if (!repoConfig) {
  repoConfig = {};
}
```

I don't plan to make config files optional at this time, because some users are installing the app for all repositories, and bulk actions can be triggered with a comment. Having a config file is also a good way to let all contributors know about the automation around the repo, and about the tools that they can use.

**Comment by PatrickHeneise** [comment]
Alright, thanks for the info! I think for private orgs, there's no need to inform contributors on a per-repo basis, so I'd rather control apps per-repo in the GitHub settings. Forking and deploying separately is the best option then, I guess.

**Comment by dessant** [comment]
I will update the `probot-config` dependency, which will allow users to create a special `.github` repository where all probot configuration files can be kept. That way you don't have to add the same config file for all repos you plan to use the app with.
